# Generated by Django 4.1.1 on 2022-09-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=300)),
                ('article', models.TimeField(blank=True)),
            ],
        ),
    ]
